### ISSUE TITLE
Could you please provide an example of using the lowlevel API

### ISSUE THREAD

**Issue by gizmomogwai** [dlang-community/dfuse#2]
e.g. I would like to intercept open calls (to track what files are accessed).
Is it also possible to just forward all not implemented functions to "normal" fs functions with the low-level API?.

**Comment by CyberShadow** [comment]
Not sure what exactly you mean by low-level API, as it could mean the C-level API (as opposed to the D high-level API which uses D classes) or the FUSE low-level API (which uses callbacks).

In any case, you probably could just look for examples in C, as (because the C API is the same regardless of the language) the code will be pretty much the same.

**Comment by gizmomogwai** [comment]
thanks .. will look into this.
